# Generated by Django 4.1.3 on 2023-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_dept', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('AT', 'Automobile Engineering')], max_length=3)),
                ('staff_designation', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50, unique=True)),
                ('staff_PhoneNo', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
