# Generated by Django 4.1.3 on 2023-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('std_name', models.CharField(max_length=50)),
                ('std_reg_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('std_dept', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('AT', 'Automobile Engineering')], max_length=3)),
                ('std_sem', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th')], max_length=1)),
                ('std_email', models.CharField(max_length=50, unique=True)),
                ('std_PhoneNo', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
