# Generated by Django 4.1.3 on 2023-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_title', models.CharField(max_length=50)),
                ('hw_desc', models.CharField(max_length=500)),
                ('hw_author', models.CharField(max_length=50)),
                ('hw_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
