# Generated by Django 4.1.3 on 2023-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studenthomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='hw_dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('AT', 'Automobile Engineering')], default=None, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='hw_sem',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
