# Generated by Django 4.1.3 on 2023-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studenthomework_hw_dept_studenthomework_hw_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthomework',
            name='id',
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='hw_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
