# Generated by Django 4.2.1 on 2023-05-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_studentreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="std_class_attended",
            field=models.IntegerField(default=0),
        ),
    ]
