# Generated by Django 4.1.3 on 2023-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('store', 'Store')], default='student', max_length=7)),
            ],
        ),
    ]
