# Generated by Django 4.2.1 on 2023-05-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TotalClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sem",
                    models.CharField(
                        choices=[
                            ("1", "1st"),
                            ("2", "2nd"),
                            ("3", "3rd"),
                            ("4", "4th"),
                            ("5", "5th"),
                            ("6", "6th"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "dept",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science and Engineering"),
                            ("ECE", "Electronics and Communication Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("AT", "Automobile Engineering"),
                        ],
                        max_length=3,
                    ),
                ),
                ("total_classes", models.IntegerField(default=0)),
            ],
        ),
    ]
